# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VegiTable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VegiTable
  pod 'SideMenu'
  pod 'Charts'
  pod 'TinyConstraints'

  target 'VegiTableTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VegiTableUITests' do
    # Pods for testing
  end

end
